version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: kafesrok-frontend
    container_name: kafesrok-frontend
    restart: unless-stopped
    ports:
      - "6001:80"
    networks:
      - coffee-net
      - web_gateway

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: kafesrok-backend
    container_name: kafesrok-backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend/storage:/var/www/html/storage
    ports:
      - "6002:80"
    environment:
      APP_NAME: KafeSrok
      APP_DEBUG: "false"
      DB_HOST: mariadb
      APP_URL: https://kafesrok.johnrak.online
      SANCTUM_STATEFUL_DOMAINS: "kafesrok.johnrak.online"
      SESSION_DOMAIN: ".johnrak.online"
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-kafesrok_production}
      DB_USERNAME: ${DB_USERNAME:-laravel}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
    depends_on:
      - mariadb
    networks:
      - coffee-net
      - web_gateway

  mariadb:
    image: mariadb:10-jammy
    container_name: kafesrok-db
    restart: unless-stopped
    ports:
      - "127.0.0.1:3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_DATABASE: ${DB_DATABASE:-kafesrok_production}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - coffee-mysql-data:/var/lib/mysql
    networks:
      - coffee-net

networks:
  coffee-net:
    driver: bridge
  web_gateway:
    external: true

volumes:
  coffee-mysql-data:
